# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TnyuxaehDLEr8lR3Zz_eE2pnPcSSFYZa
"""

import re
import requests

def check_phishing_url(url):
    with open("/content/phishing-domains-ACTIVE.txt", "r") as f:
        malicious_urls = f.read().splitlines()


    if url in malicious_urls:
        return True

    suspicious_patterns = [
        r"https?://(?:www\.)?(?:login|account)\.\w+\.\w+",
        r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"
    ]

    for pattern in suspicious_patterns:
        if re.search(pattern, url):
            return True

    return False

import hashlib

def analyze_file(file_path):

    with open(file_path, "rb") as f:
        bytes = f.read()
        file_hash = hashlib.sha256(bytes).hexdigest()


    with open("/content/full-hash-sha256-aa.txt", "r") as f:
        malicious_hashes = f.read().splitlines()

    return file_hash in malicious_hashes

def scan_logs(log_file):
    keywords = ["unauthorized", "breach", "admin", "root", "access denied"]
    alerts = []

    with open(log_file, "r") as f:
        for line in f:
            for keyword in keywords:
                if keyword in line.lower():
                    alerts.append(line.strip())
                    break

    return alerts

if __name__ == "__main__":

    test_url = "0000000o.weebly.com"
    print(f"Phishing check: {check_phishing_url(test_url)}")


    print(f"Malware detected: {analyze_file('/content/windows.exe')}")